//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class CIOStateMsg : Message
    {
        public const string k_RosMessageName = "xarm_msgs/CIOState";
        public override string RosMessageName => k_RosMessageName;

        public HeaderMsg header;
        //  contorller gpio module state
        public short state;
        //  controller gpio module error code
        public short code;
        //  input_digitals[0]: digital input functional gpio state
        //  input_digitals[1]: digital input configuring gpio state
        //     CI0: (input_digitals[1] >> 0) & 0x0001
        //     CI1: (input_digitals[1] >> 1) & 0x0001
        //     CI7: (input_digitals[1] >> 7) & 0x0001
        //     DI0: (input_digitals[1] >> 8) & 0x0001
        //     DI1: (input_digitals[1] >> 9) & 0x0001
        //     DI7: (input_digitals[1] >> 15) & 0x0001
        public ushort[] input_digitals;
        //  output_digitals[0]: digital output functional gpio state
        //  output_digitals[1]: digital output configuring gpio state
        //     CO0: (output_digitals[1] >> 0) & 0x0001
        //     CO1: (output_digitals[1] >> 1) & 0x0001
        //     CO7: (output_digitals[1] >> 7) & 0x0001
        //     DO0: (output_digitals[1] >> 8) & 0x0001
        //     DO1: (output_digitals[1] >> 9) & 0x0001
        //     DO7: (output_digitals[1] >> 15) & 0x0001
        public ushort[] output_digitals;
        //  input_analogs[0]: the value of AI0
        //  input_analogs[1]: the value of AI1
        public float[] input_analogs;
        //  output_analogs[0]: the value of AO0
        //  output_analogs[1]: the value of AO1
        public float[] output_analogs;
        //  digital input functional info
        public byte[] input_conf;
        //  digital output functional info
        public byte[] output_conf;

        public CIOStateMsg()
        {
            this.header = new HeaderMsg();
            this.state = 0;
            this.code = 0;
            this.input_digitals = new ushort[2];
            this.output_digitals = new ushort[2];
            this.input_analogs = new float[2];
            this.output_analogs = new float[2];
            this.input_conf = new byte[16];
            this.output_conf = new byte[16];
        }

        public CIOStateMsg(HeaderMsg header, short state, short code, ushort[] input_digitals, ushort[] output_digitals, float[] input_analogs, float[] output_analogs, byte[] input_conf, byte[] output_conf)
        {
            this.header = header;
            this.state = state;
            this.code = code;
            this.input_digitals = input_digitals;
            this.output_digitals = output_digitals;
            this.input_analogs = input_analogs;
            this.output_analogs = output_analogs;
            this.input_conf = input_conf;
            this.output_conf = output_conf;
        }

        public static CIOStateMsg Deserialize(MessageDeserializer deserializer) => new CIOStateMsg(deserializer);

        private CIOStateMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.state);
            deserializer.Read(out this.code);
            deserializer.Read(out this.input_digitals, sizeof(ushort), 2);
            deserializer.Read(out this.output_digitals, sizeof(ushort), 2);
            deserializer.Read(out this.input_analogs, sizeof(float), 2);
            deserializer.Read(out this.output_analogs, sizeof(float), 2);
            deserializer.Read(out this.input_conf, sizeof(byte), 16);
            deserializer.Read(out this.output_conf, sizeof(byte), 16);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.state);
            serializer.Write(this.code);
            serializer.Write(this.input_digitals);
            serializer.Write(this.output_digitals);
            serializer.Write(this.input_analogs);
            serializer.Write(this.output_analogs);
            serializer.Write(this.input_conf);
            serializer.Write(this.output_conf);
        }

        public override string ToString()
        {
            return "CIOStateMsg: " +
            "\nheader: " + header.ToString() +
            "\nstate: " + state.ToString() +
            "\ncode: " + code.ToString() +
            "\ninput_digitals: " + System.String.Join(", ", input_digitals.ToList()) +
            "\noutput_digitals: " + System.String.Join(", ", output_digitals.ToList()) +
            "\ninput_analogs: " + System.String.Join(", ", input_analogs.ToList()) +
            "\noutput_analogs: " + System.String.Join(", ", output_analogs.ToList()) +
            "\ninput_conf: " + System.String.Join(", ", input_conf.ToList()) +
            "\noutput_conf: " + System.String.Join(", ", output_conf.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
