//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmGripper
{
    [Serializable]
    public class MoveResult : Message
    {
        public const string k_RosMessageName = "xarm_gripper/Move";
        public override string RosMessageName => k_RosMessageName;

        public bool success;
        public short err_code;

        public MoveResult()
        {
            this.success = false;
            this.err_code = 0;
        }

        public MoveResult(bool success, short err_code)
        {
            this.success = success;
            this.err_code = err_code;
        }

        public static MoveResult Deserialize(MessageDeserializer deserializer) => new MoveResult(deserializer);

        private MoveResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.err_code);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.err_code);
        }

        public override string ToString()
        {
            return "MoveResult: " +
            "\nsuccess: " + success.ToString() +
            "\nerr_code: " + err_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
