//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmGripper
{
    [Serializable]
    public class MoveFeedback : Message
    {
        public const string k_RosMessageName = "xarm_gripper/Move";
        public override string RosMessageName => k_RosMessageName;

        public float current_pulse;

        public MoveFeedback()
        {
            this.current_pulse = 0.0f;
        }

        public MoveFeedback(float current_pulse)
        {
            this.current_pulse = current_pulse;
        }

        public static MoveFeedback Deserialize(MessageDeserializer deserializer) => new MoveFeedback(deserializer);

        private MoveFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.current_pulse);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_pulse);
        }

        public override string ToString()
        {
            return "MoveFeedback: " +
            "\ncurrent_pulse: " + current_pulse.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
