//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class FtCaliLoadRequest : Message
    {
        public const string k_RosMessageName = "xarm_msgs/FtCaliLoad";
        public override string RosMessageName => k_RosMessageName;

        //  This format is suitable for the following services
        //    - ft_sensor_cali_load
        //  iden result([mass(kg)，x_centroid(mm)，y_centroid(mm)，z_centroid(mm)，Fx_offset，Fy_offset，Fz_offset，Tx_offset，Ty_offset，Tz_ffset])
        public float[] datas;
        //  whether to convert the paramster to the corresponding tcp load and set
        public bool association_setting_tcp_load;
        //  float32 m   0.325
        //  float32 x   -17.0
        //  float32 y   9.0
        //  float32 z   11.8

        public FtCaliLoadRequest()
        {
            this.datas = new float[0];
            this.association_setting_tcp_load = false;
        }

        public FtCaliLoadRequest(float[] datas, bool association_setting_tcp_load)
        {
            this.datas = datas;
            this.association_setting_tcp_load = association_setting_tcp_load;
        }

        public static FtCaliLoadRequest Deserialize(MessageDeserializer deserializer) => new FtCaliLoadRequest(deserializer);

        private FtCaliLoadRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.datas, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.association_setting_tcp_load);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.datas);
            serializer.Write(this.datas);
            serializer.Write(this.association_setting_tcp_load);
        }

        public override string ToString()
        {
            return "FtCaliLoadRequest: " +
            "\ndatas: " + System.String.Join(", ", datas.ToList()) +
            "\nassociation_setting_tcp_load: " + association_setting_tcp_load.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
