//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class FtIdenLoadRequest : Message
    {
        public const string k_RosMessageName = "xarm_msgs/FtIdenLoad";
        public override string RosMessageName => k_RosMessageName;

        //  This format is suitable for the following services
        //    - ft_sensor_iden_load

        public FtIdenLoadRequest()
        {
        }
        public static FtIdenLoadRequest Deserialize(MessageDeserializer deserializer) => new FtIdenLoadRequest(deserializer);

        private FtIdenLoadRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "FtIdenLoadRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
