//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class FtIdenLoadResponse : Message
    {
        public const string k_RosMessageName = "xarm_msgs/FtIdenLoad";
        public override string RosMessageName => k_RosMessageName;

        public short ret;
        public string message;
        //  the result of identification
        //    ft_sensor_iden_load: [mass(kg)，x_centroid(mm)，y_centroid(mm)，z_centroid(mm)，Fx_offset，Fy_offset，Fz_offset，Tx_offset，Ty_offset，Tz_ffset]
        public float[] datas;

        public FtIdenLoadResponse()
        {
            this.ret = 0;
            this.message = "";
            this.datas = new float[0];
        }

        public FtIdenLoadResponse(short ret, string message, float[] datas)
        {
            this.ret = ret;
            this.message = message;
            this.datas = datas;
        }

        public static FtIdenLoadResponse Deserialize(MessageDeserializer deserializer) => new FtIdenLoadResponse(deserializer);

        private FtIdenLoadResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ret);
            deserializer.Read(out this.message);
            deserializer.Read(out this.datas, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ret);
            serializer.Write(this.message);
            serializer.WriteLength(this.datas);
            serializer.Write(this.datas);
        }

        public override string ToString()
        {
            return "FtIdenLoadResponse: " +
            "\nret: " + ret.ToString() +
            "\nmessage: " + message.ToString() +
            "\ndatas: " + System.String.Join(", ", datas.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
