//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GetFloat32ListRequest : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GetFloat32List";
        public override string RosMessageName => k_RosMessageName;

        //  This format is suitable for the following services
        //    - get_position
        //    - get_servo_angle
        //    - get_position_aa

        public GetFloat32ListRequest()
        {
        }
        public static GetFloat32ListRequest Deserialize(MessageDeserializer deserializer) => new GetFloat32ListRequest(deserializer);

        private GetFloat32ListRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetFloat32ListRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
