//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GetFloat32ListResponse : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GetFloat32List";
        public override string RosMessageName => k_RosMessageName;

        public short ret;
        public string message;
        public float[] datas;

        public GetFloat32ListResponse()
        {
            this.ret = 0;
            this.message = "";
            this.datas = new float[0];
        }

        public GetFloat32ListResponse(short ret, string message, float[] datas)
        {
            this.ret = ret;
            this.message = message;
            this.datas = datas;
        }

        public static GetFloat32ListResponse Deserialize(MessageDeserializer deserializer) => new GetFloat32ListResponse(deserializer);

        private GetFloat32ListResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ret);
            deserializer.Read(out this.message);
            deserializer.Read(out this.datas, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ret);
            serializer.Write(this.message);
            serializer.WriteLength(this.datas);
            serializer.Write(this.datas);
        }

        public override string ToString()
        {
            return "GetFloat32ListResponse: " +
            "\nret: " + ret.ToString() +
            "\nmessage: " + message.ToString() +
            "\ndatas: " + System.String.Join(", ", datas.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
