//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GetInt32Request : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GetInt32";
        public override string RosMessageName => k_RosMessageName;


        public GetInt32Request()
        {
        }
        public static GetInt32Request Deserialize(MessageDeserializer deserializer) => new GetInt32Request(deserializer);

        private GetInt32Request(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetInt32Request: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
