//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GetInt32Response : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GetInt32";
        public override string RosMessageName => k_RosMessageName;

        public int data;
        public short ret;
        public string message;

        public GetInt32Response()
        {
            this.data = 0;
            this.ret = 0;
            this.message = "";
        }

        public GetInt32Response(int data, short ret, string message)
        {
            this.data = data;
            this.ret = ret;
            this.message = message;
        }

        public static GetInt32Response Deserialize(MessageDeserializer deserializer) => new GetInt32Response(deserializer);

        private GetInt32Response(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data);
            deserializer.Read(out this.ret);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
            serializer.Write(this.ret);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "GetInt32Response: " +
            "\ndata: " + data.ToString() +
            "\nret: " + ret.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
