//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class GetSetModbusDataResponse : Message
    {
        public const string k_RosMessageName = "xarm_msgs/GetSetModbusData";
        public override string RosMessageName => k_RosMessageName;

        public short ret;
        public string message;
        public byte[] respond_data;

        public GetSetModbusDataResponse()
        {
            this.ret = 0;
            this.message = "";
            this.respond_data = new byte[0];
        }

        public GetSetModbusDataResponse(short ret, string message, byte[] respond_data)
        {
            this.ret = ret;
            this.message = message;
            this.respond_data = respond_data;
        }

        public static GetSetModbusDataResponse Deserialize(MessageDeserializer deserializer) => new GetSetModbusDataResponse(deserializer);

        private GetSetModbusDataResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.ret);
            deserializer.Read(out this.message);
            deserializer.Read(out this.respond_data, sizeof(byte), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.ret);
            serializer.Write(this.message);
            serializer.WriteLength(this.respond_data);
            serializer.Write(this.respond_data);
        }

        public override string ToString()
        {
            return "GetSetModbusDataResponse: " +
            "\nret: " + ret.ToString() +
            "\nmessage: " + message.ToString() +
            "\nrespond_data: " + System.String.Join(", ", respond_data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
