//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class SetControllerAnalogIORequest : Message
    {
        public const string k_RosMessageName = "xarm_msgs/SetControllerAnalogIO";
        public override string RosMessageName => k_RosMessageName;

        //  Setting the analog Output port value at robot controller, io_num: from 1 to 2
        public short port_num;
        public float analog_value;

        public SetControllerAnalogIORequest()
        {
            this.port_num = 0;
            this.analog_value = 0.0f;
        }

        public SetControllerAnalogIORequest(short port_num, float analog_value)
        {
            this.port_num = port_num;
            this.analog_value = analog_value;
        }

        public static SetControllerAnalogIORequest Deserialize(MessageDeserializer deserializer) => new SetControllerAnalogIORequest(deserializer);

        private SetControllerAnalogIORequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.port_num);
            deserializer.Read(out this.analog_value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.port_num);
            serializer.Write(this.analog_value);
        }

        public override string ToString()
        {
            return "SetControllerAnalogIORequest: " +
            "\nport_num: " + port_num.ToString() +
            "\nanalog_value: " + analog_value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
