//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Xarm
{
    [Serializable]
    public class SetFloat32Request : Message
    {
        public const string k_RosMessageName = "xarm_msgs/SetFloat32";
        public override string RosMessageName => k_RosMessageName;

        //  request: set single floating point parameters.
        //  data: floating point (32-bit) parameter value.
        public float data;

        public SetFloat32Request()
        {
            this.data = 0.0f;
        }

        public SetFloat32Request(float data)
        {
            this.data = data;
        }

        public static SetFloat32Request Deserialize(MessageDeserializer deserializer) => new SetFloat32Request(deserializer);

        private SetFloat32Request(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "SetFloat32Request: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
