//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmPlanner
{
    [Serializable]
    public class exec_planRequest : Message
    {
        public const string k_RosMessageName = "xarm_planner/exec_plan";
        public override string RosMessageName => k_RosMessageName;

        public bool exec;

        public exec_planRequest()
        {
            this.exec = false;
        }

        public exec_planRequest(bool exec)
        {
            this.exec = exec;
        }

        public static exec_planRequest Deserialize(MessageDeserializer deserializer) => new exec_planRequest(deserializer);

        private exec_planRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.exec);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.exec);
        }

        public override string ToString()
        {
            return "exec_planRequest: " +
            "\nexec: " + exec.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
