//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmPlanner
{
    [Serializable]
    public class joint_planRequest : Message
    {
        public const string k_RosMessageName = "xarm_planner/joint_plan";
        public override string RosMessageName => k_RosMessageName;

        //  list of target joint positions in radian.
        public double[] target;

        public joint_planRequest()
        {
            this.target = new double[0];
        }

        public joint_planRequest(double[] target)
        {
            this.target = target;
        }

        public static joint_planRequest Deserialize(MessageDeserializer deserializer) => new joint_planRequest(deserializer);

        private joint_planRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.target, sizeof(double), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.target);
            serializer.Write(this.target);
        }

        public override string ToString()
        {
            return "joint_planRequest: " +
            "\ntarget: " + System.String.Join(", ", target.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
