//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmPlanner
{
    [Serializable]
    public class pose_planResponse : Message
    {
        public const string k_RosMessageName = "xarm_planner/pose_plan";
        public override string RosMessageName => k_RosMessageName;

        public bool success;

        public pose_planResponse()
        {
            this.success = false;
        }

        public pose_planResponse(bool success)
        {
            this.success = success;
        }

        public static pose_planResponse Deserialize(MessageDeserializer deserializer) => new pose_planResponse(deserializer);

        private pose_planResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "pose_planResponse: " +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
