//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.XarmPlanner
{
    [Serializable]
    public class single_straight_planRequest : Message
    {
        public const string k_RosMessageName = "xarm_planner/single_straight_plan";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg target;

        public single_straight_planRequest()
        {
            this.target = new Geometry.PoseMsg();
        }

        public single_straight_planRequest(Geometry.PoseMsg target)
        {
            this.target = target;
        }

        public static single_straight_planRequest Deserialize(MessageDeserializer deserializer) => new single_straight_planRequest(deserializer);

        private single_straight_planRequest(MessageDeserializer deserializer)
        {
            this.target = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target);
        }

        public override string ToString()
        {
            return "single_straight_planRequest: " +
            "\ntarget: " + target.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
